### Create new inventory
# Request
POST http://localhost:3001/inventory
content-type: application/json

# Response
{
    "quantity": 3,
    "itemId": "clrx78uxu0000rlixex1m5dg2",
    "userId": "clrwovsej0000dfv7t13tqj4l"
}
### Get all inventory
# Request
GET http://localhost:3001/inventory

### Get all inventory via item id 
# Request
GET http://localhost:3001/inventory/item/clrx78uxu0000rlixex1m5dg2

### Get inventory via id
# Request
GET http://localhost:3001/inventory/clrx87eey00002gtc6vkvr2o7

### Update inventory via id
# Request 
PUT http://localhost:3001/inventory/clrx87eey00002gtc6vkvr2o7
content-type: application/json
# Response

{
    "type": "ACCESSORY",
    "name": "Cat Ears" 
}

### Delete inventory via id 
# Request 
DELETE http://localhost:3001/inventory/clrx75pib0000l3j9hiwrt60y