### Description: Add user to relations
## Request 
POST http://localhost:3001/relationships 
## Response 
content-type: application/json

{
    "userId": "clte5s2lp0000st8dcrhqf8jt", 
    "friendId": "clte5s2ly0001st8dmvgw34i0", 
    "status": "PENDING",
    "updatedAt": "1997-07-16T19:20:30.451Z"
}

### Description: Update user relationships
## Request 
PUT http://localhost:3001/relationships 
## Response 
content-type: application/json

{
    "userId": "clte5s2lp0000st8dcrhqf8jt", 
    "friendId": "clte5s2ly0001st8dmvgw34i0", 
    "status": "CONFIRMED",
    "updatedAt": "1997-07-16T19:20:30.451Z"
}

### Description: Get all relationships 
## Request 
GET http://localhost:3001/relationships 

### Description: Get all relationships 
## Request 
GET http://localhost:3001/relationships/status/
## Response 
content-type: application/json

{
    "status": "CONFIRMED"
} 


### Description: Get relationship via id 
## Request 
GET http://localhost:3001/relationships/cltkruw4j0003cuamhbog2zcm

### Description: Delete relationship
## Request 
DELETE http://localhost:3001/relationships/
content-type: application/json

{
    "userId": "clte5s2lp0000st8dcrhqf8jt", 
    "friendId": "clte5s2ly0001st8dmvgw34i0" 
}
