### Description: Send relationship request 
## Request 
POST http://localhost:3001/relationships 
## Response 
content-type: application/json

{
    "fromUserId": "clt9gy1zx0000tcmzs7g5q4vo",
    "toUserId": "clt9gv5vx0000bo7rprjg9uaw"
}

### Description: Get all relationships 
## Request 
GET http://localhost:3001/relationships 

### Description: Get all relationships 
## Request 
GET http://localhost:3001/relationships/status/
## Response 
content-type: application/json

{
    "status": "CONFIRMED"
} 


### Description: Get relationship via id 
## Request 
GET http://localhost:3001/relationships/clrxbkho40002ay6fuuunnd62

### Description: Update relationship request 
## Request 
PUT http://localhost:3001/relationships/accept/cls8j7p5f000313qooidof49v
## Response 
content-type: application/json

{
    "status": "CONFIRMED"
} 

### Description: Update relationship request 
## Request 
DELETE http://localhost:3001/relationships/clt9sfly3000113bckc6es85s
