### Description: Retrieve all users 
## Request
GET http://localhost:3001/users

### Description: Retrieve user via id 
## Request 
GET http://localhost:3001/users/clt9gy1zx0000tcmzs7g5q4vo

### Description: Retrieve user via username 
## Request 
GET http://localhost:3001/users/username/marydeer


### Description: Create user 
## Request 
POST http://localhost:3001/users 
## Response 
content-type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "username": "johnsmith", 
    "email": "johnsmith@example.com",
    "password": "password"
}

### Description: Update user via id 
## Request 
PUT http://localhost:3001/users/cls5uk5us0000gelocbybczzj
## Response
content-type: application/json

{
    "firstName": "Mary",
    "lastName": "Smith",
    "email": "marysmith@example.com",
    "password": "password"
}

### Description: Delete user via id 
## Request
DELETE http://localhost:3001/users/clrlbn1kk00004dkbptu7t9rm