### Definition: List all notifications 
## Request 
GET http://localhost:3001/notifications

### Definition: List all notifications via userId 
## Request 
GET http://localhost:3001/notifications/user/clspfh9em00004ju0nwklyklg

### Definition: List notification via id 
## Request 
GET http://localhost:3001/notifications/clspgzfu90003dmqvthrang2j

### Definition: Create notification  
## Request 
POST http://localhost:3001/notifications 
## Response 
content-type: application/json

{
    "name": "Advil",
    "type": "Medicine",
    "quantity": 2,
    "unit": "pills" ,
    "notes": "",
    "photos": "",
    "dosageQuantity": "2",
    "dosageUnit": "mg",
    "frequencyQuantity": "2",
    "frequencyUnit": "Daily",
    "day": "undefined",
    "endDate": "undefined",
    "repeating": "undefined",
    "time": "14:15",
    "userId": "clspfh9em00004ju0nwklyklg",
    "petId": "clspggxx80000xwjdlinq5by6"
}

### Definition: Update notification via id
## Request 
PUT http://localhost:3001/notifications/clrlb5jen0000t2gx0nmybncc
## Response 
content-type: application/json

{
    "name": "Ibuprofen", 
    "type": "MEDICINE",
    "quantity": 2,
    "unit": "tablets" 
}

### Definition: Delete notification via id  
## Request 
DELETE http://localhost:3001/notifications/clspflx5v00044ju0x4wyuzfb