### Definition: List all notifications 
## Request 
GET http://localhost:3001/notifications

### Definition: List all notifications via userId 
## Request 
GET http://localhost:3001/notifications/user/clte5s2lp0000st8dcrhqf8jt

### Definition: List notification via id 
## Request 
GET http://localhost:3001/notifications/cltqepwj00000cmmqwpfoktjj

### Definition: Create notification  
## Request 
POST http://localhost:3001/notifications 
## Response 
content-type: application/json

{
    "name": "Advil",
    "type": "Medicine",
    "quantity": 2,
    "unit": "pills" ,
    "notes": "",
    "photos": "",
    "dosageQuantity": 2,
    "dosageUnit": "mg",
    "frequencyQuantity": 2,
    "frequencyUnit": "Daily",
    "day": "undefined",
    "endDate": "undefined",
    "repeating": "undefined",
    "time": "14:15",
    "userId": "clte5s2lp0000st8dcrhqf8jt",
    "petId": "clte5y7f6000113wkfx3ujf4h"
}

### Definition: Update notification via id
## Request 
PUT http://localhost:3001/notifications/cclte6e5a30002mm6f3sgcemgr
## Response 
content-type: application/json

{
    "name": "Advil",
    "type": "Medicine",
    "quantity": 2,
    "unit": "pills" ,
    "notes": "",
    "photos": "",
    "dosageQuantity": "2",
    "dosageUnit": "mg",
    "frequencyQuantity": "2",
    "frequencyUnit": "Daily",
    "day": "",
    "endDate": "",
    "repeating": "Daily",
    "time": "14:15",
    "userId": "clte5s2lp0000st8dcrhqf8jt",
    "petId": "clte5y7f6000113wkfx3ujf4h"
}

### Definition: Delete notification via id  
## Request 
DELETE http://localhost:3001/notifications/cltjghyc300011t2fv83cfxm2