### Definition: List all medicines 
## Request 
GET http://localhost:3001/medicines

### Definition: List medicine 
## Request 
GET http://localhost:3001/medicines/clriwgvip0005dkn60qn4m8xs

### Definition: Create medicine  
## Request 
POST http://localhost:3001/medicines 
## Response 
content-type: application/json

{
    "name": "Advil", 
    "quantity": 2, 
    "unit": "pills", 
    "petId": "clrjqerr70009ai5iejju6hcl"
}

### Definition: Update medicine  
## Request 
PUT http://localhost:3001/medicines/clriwgvip0005dkn60qn4m8xs
## Response 
content-type: application/json

{
    "name": "Ibuprofen", 
    "quantity": 2, 
    "unit": "tablets", 
    "petId": "clriweg820004ai5icuy1irv2"
}

### Definition: Delete medicine 
## Request 
DELETE http://localhost:3001/medicines/clrjq3lbc000114ileol8vvci