### Description: Retrieve all pets
## Request
GET http://localhost:3001/pets

### Description: Retrieve pet via user id 
## Request 
GET http://localhost:3001/pets/clrjqerr70009ai5iejju6hcl

### Description: Create pet 
## Request 
POST http://localhost:3001/pets 
## Response 
content-type: application/json

{
    "firstName": "Toasty", 
    "lastName": "Smithy", 
    "breed": "Bengal", 
    "type": "CAT", 
    "birthday": "02-12-2013", 
    "gotchaDate": "02-12-2013", 
    "primaryOwnerId": "clrpdcss50001h9t29a1it28q"
}

### Description: Update pet via id 
## Request 
PUT http://localhost:3001/pets/clrmmvx8l0003e76z671ioo5e
## Response
content-type: application/json

{
    "firstName": "Toast", 
    "lastName": "Smithy", 
    "breed": "Bengal", 
    "type": "CAT", 
    "birthday": "10/10/2000",
    "gotchaDate": "10/31/2001",
    "primaryOwnerId": "clrldpsxi000210fkmg5vvith" 
}

### Description: Delete pet via id 
## Request
DELETE http://localhost:3001/pets/clrmmntrr0008wwynjarh58c2