### Definition: List all medicines 
## Request 
GET http://localhost:3001/medicines

### Definition: List medicine via id 
## Request 
GET http://localhost:3001/medicines/clrml73zj0000gv0c3bzzwj0y

### Definition: Create medicine  
## Request 
POST http://localhost:3001/medicines 
## Response 
content-type: application/json

{
    "name": "Advil",
    "quantity": 2,
    "unit": "pills" 
}

### Definition: Update medicine via id
## Request 
PUT http://localhost:3001/medicines/clrlb5jen0000t2gx0nmybncc
## Response 
content-type: application/json

{
    "name": "Ibuprofen", 
    "quantity": 2,
    "unit": "tablets" 
}

### Definition: Delete medicine via id  
## Request 
DELETE http://localhost:3001/medicines/clrlxjcm70000k59g43phb4oo