### Definition: List all medicineNotifications
## Request 
GET http://localhost:3001/medicineNotifications

### Definition: List all medicineNotifications via medicineId
## Request 
GET http://localhost:3001/medicineNotifications/clrml73zj0000gv0c3bzzwj0y

### Definition: List medicineNotifications via id 
## Request 
GET http://localhost:3001/medicineNotifications/clrlb5jen0000t2gx0nmybncc

### Definition: Create medicineNotifications 
## Request 
POST http://localhost:3001/medicineNotifications
## Response 
content-type: application/json

{
    "day": "Monday",
    "hour": 2,
    "minute": 45,
    "timeOfDay": "PM",
    "endDate": "1/23/2024", 
    "medicineDetailId": "clro0sh1q000210grfg12ojlh"
}

### Definition: Update medicineNotifications via id
## Request 
PUT http://localhost:3001/medicineNotifications/clrmodkgb000168ojmllgmham
## Response 
content-type: application/json

{
    "dosageQuantity": 1,
    "dosageUnit": "mg",
    "frequencyQuantity": 2,
    "frequencyUnit": "WEEK",
    "medicineId": "clrmoepka0000921njwk0fep0"
}

### Definition: Delete medicineNotifications via id  
## Request 
DELETE http://localhost:3001/medicineNotifications/clrmmkwid0002wwyn0vmnopg4